### ISSUE TITLE
Issue on providing Swagger docs

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-tumblebug-api-web#13]
[현황]
관리 point 가 여러 곳에 존재합니다.

- ...
- [cb-ladybug/src/docs/](https://github.com/cloud-barista/cb-ladybug/tree/master/src/docs)
- [cb-tumblebug/src/docs/](https://github.com/cloud-barista/cb-tumblebug/tree/master/src/docs)

![image](https://user-images.githubusercontent.com/46767780/108142031-4d91a600-7108-11eb-9ae4-a50b82852e6b.png)

---

- ...
- [cb-ladybug-api-web/](https://github.com/cloud-barista/cb-ladybug-api-web)
- [cb-tumblebug-api-web/](https://github.com/cloud-barista/cb-tumblebug-api-web)

![image](https://user-images.githubusercontent.com/46767780/108142409-0eb02000-7109-11eb-93bb-643a424bcece.png)

**Comment by jihoon-seo** [comment]
[제안]

1. `swagger-github-pages` 기능을 제공하는 repo는
   - 1개만 유지
   - 공동 활용
   - repo 안에 TB, Ladybug 등의 YAML 파일을 두지 않음
2. 다음과 같이, 각 repo (TB, Ladybug, ...) 의 tag 별 `swagger.yaml` 의 내용을 출력하도록 링크 제공
   - Latest TB MCIR image API: https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/master/src/docs/swagger.yaml#/Image
   - TB MCIR image API v0.3.0: https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/v0.3.0-espresso/src/docs/swagger.yaml#/Image
   - TB MCIR image API v0.2.9: https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cb-tumblebug/v0.2.9/src/docs/swagger.yaml#/Image
   - Latest CB-Ladybug API: https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cb-ladybug/master/src/docs/swagger.yaml
   - CB-Ladybug API v0.3.0: https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cb-ladybug/v0.3.0-espresso/src/docs/swagger.yaml
   - CB-Ladybug API v0.2.8: https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cb-ladybug/v0.2.8/src/docs/swagger.yaml
   - ...

---

이렇게 하면, `swagger-0.3.0-espresso.yaml` 와 같은 파일들을 관리하지 않아도 됩니다.

**Comment by seokho-son** [comment]
@jihoon-seo 감사합니다. 동의합니다..^^ 다만 TB와 같은 API 웹사이트 제공 방식이 모든 FW에서 적용되는 것이 아니므로, 상황을 좀 살펴보면 어떨까 싶습니다. 어떠신지요?
